spring:
  config:
    import: "optional:configserver:http://config-server:8888"
  datasource:
    url: jdbc:mysql://mysql:3306/pcms_notification?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: pcms_user
    password: pcms_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
