spring:
  config:
    import: "optional:configserver:http://config-server:8888"
  datasource:
    url: jdbc:mysql://mysql:3306/pcms_catalog?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

pcms:
  catalog:
    image-upload-dir: uploads/medicines
