spring:
  config:
    import: "optional:configserver:http://config-server:8888"
  datasource:
    url: jdbc:mysql://mysql:3306/pcms_order?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
