-- ============================================================================
-- PCMS Admin User Seed Script
-- Creates default admin + pharmacist users for local development & testing.
--
-- Passwords (BCrypt strength = 10, verified against the hashes below):
--   admin@pcms.vn        : admin123
--   pharmacist01@pcms.vn : pharma123
--
-- Hashes were generated by Spring's BCryptPasswordEncoder (see
-- scripts/GenerateSeedHash.java). If you need to regenerate them, run the
-- Java helper in `scripts/GenerateSeedHash.java` or, alternatively, use
-- the equivalent Node.js one-liner:
--   node -e "const b=require('bcryptjs'); console.log(b.hashSync('admin123',10));"
-- ============================================================================
USE pcms_user;

INSERT INTO users (id, email, password_hash, full_name, phone, role, status, email_verified, created_at, updated_at)
VALUES (
    UUID_TO_BIN(UUID(), 1),
    'admin@pcms.vn',
    '$2a$10$6yDocMLWwXDCp9sfBjmsiey.JMDeR.k.mVzA4EU.70V/Ow11vPML2',
    'System Administrator',
    '0901234567',
    'ADMIN',
    'ACTIVE',
    1,
    NOW(),
    NOW()
) ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), updated_at = NOW();

INSERT INTO users (id, email, password_hash, full_name, phone, role, status, email_verified, created_at, updated_at)
VALUES (
    UUID_TO_BIN(UUID(), 1),
    'pharmacist01@pcms.vn',
    '$2a$10$bSTzFttm6asD/O/O/UqwFuofbDtnuRjO0s7Ku4E4MKA0W0PhP.j5m',
    'Nguyễn Văn A',
    '0901234567',
    'PHARMACIST',
    'ACTIVE',
    1,
    NOW(),
    NOW()
) ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), updated_at = NOW();

SELECT 'Admin + pharmacist users seeded successfully' AS status;