server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  autoconfigure:
    exclude:
      - org.springframework.cloud.config.server.config.EnvironmentRepositoryConfiguration$GitRepositoryConfiguration
      - org.springframework.cloud.config.server.config.EnvironmentRepositoryConfiguration$JGitRepositoryConfiguration
      - org.springframework.cloud.config.server.config.EnvironmentRepositoryConfiguration$SvnRepositoryConfiguration
      - org.springframework.cloud.config.server.config.EnvironmentRepositoryConfiguration$VaultRepositoryConfiguration
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config,file:./config

management:
  endpoints:
    web:
      exposure:
        include: "*"
